In [77]:
import numpy as np

In [78]:
alf = 'abcdefghijklmnopqrstuvwxyvç ,ãé'

alf_array = []

for i in range(len(alf)):
    l = list()
    for n in range(len(alf)):
        if n==i:
            l.append(1)
        else:
            l.append(0)
    alf_array.append(l)

alfabeto_ident = np.array(alf_array)
alfabeto_ident

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0,

In [79]:
encoder = np.roll(alfabeto_ident,-5,1)
encoder

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0,

In [80]:
encoder2 = np.roll(alfabeto_ident,-3,1)
encoder2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0,

In [81]:
def para_one_hot(msg):
    l = list()
    for a in msg:
        i = alf.index(a)
        l.append(alfabeto_ident[i])
    l = np.array(l)
    return l.transpose()

In [102]:
def para_string(array):
    saida = ''
    array = array.transpose()
    for l in array:
        saida+=alf[np.where(l == 1)[0][0]]
    return saida

In [103]:
para_string(alfabeto_ident)

'abcdefghijklmnopqrstuvwxyvç ,ãé'

In [85]:
def cifrar(msg, P):
    msg = para_one_hot(msg)
    saida = np.dot(P,msg)
    return para_string(saida)

In [107]:
p = cifrar('caça',encoder)
print(p)

hfaf


In [108]:
def de_cifrar(msg,P):
    return para_string(np.dot(np.linalg.inv(P),para_one_hot(msg)))

In [109]:
de_cifrar(p,encoder)

'caça'

In [98]:
def enigma_simples(msg,P,E):
    msg = para_one_hot(msg)
    m_ = E@P@msg
    return para_string(m_)

In [112]:
i = enigma_simples('enfiou mas foi pouco',encoder,encoder2)
print(i)

mvnqw,euiçenwqexw,kw


In [113]:
def de_nigma_simples(msg,P,E):
    msg = para_one_hot(msg)
    m_ = np.linalg.inv(P)@np.linalg.inv(E)@msg
    return para_string(m_)

In [114]:
de_nigma_simples(i,encoder,encoder2)

'enfiou mas foi pouco'

In [163]:
def enigma(msg,P,E):
    n = len(msg)
    msg = para_one_hot(msg)
    cont = 0
    final = list()
    for i in range(n):
        c = E
        for _ in range(cont):
            c=c@E
        l = msg[:,i].transpose()
        arr = c@P@l
        final.append(arr)
        cont+=1

    return para_string(np.array(final).transpose())

In [164]:
teste = enigma("abcde",encoder,encoder2)
print(teste)

imquy


In [171]:
def de_nigma(msg,P,E):
    n = len(msg)
    msg = para_one_hot(msg)
    cont=0
    saida = list()
    e_ = np.linalg.inv(E)
    p_ = np.linalg.inv(P)
    for i in range(n):
        c = e_
        for _ in range(cont):
            c=c@e_
        l = msg[:,i].transpose()
        arr = p_@c@l
        saida.append(arr)
        cont+=1
    
    return para_string(np.array(saida).transpose())

In [172]:
de_nigma(teste,encoder,encoder2)

'abcde'